[project]
name = "ssr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]
