name = "synthetic-market-research-backend"
main = "src/index.ts"
compatibility_date = "2024-10-15"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8788

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionObject"

[vars]
PYTHON_API_URL = "https://your-python-api.workers.dev"
ENVIRONMENT = "development"

[[migrations]]
tag = "v1"
new_classes = ["SessionObject"]
