class DemographicProfiles:
    PROFILES = {
        "1": {
            "age": 32,
            "gender": "female",
            "income": "$72k",
            "location": "San Francisco",
            "occupation": "software engineer",
            "education": "bachelor’s",
            "interests": ["hiking", "yoga", "tech gadgets", "travel", "sustainability"],
        },
        "2": {
            "age": 45,
            "gender": "male",
            "income": "$50k",
            "location": "Detroit",
            "occupation": "car mechanic",
            "education": "trade school",
            "interests": ["craft beer", "cars", "rock", "fast food", "darts", "family"],
        },
        "3": {
            "age": 21,
            "gender": "female",
            "income": "$18k",
            "location": "Austin",
            "occupation": "college student",
            "education": "undergraduate",
            "interests": [
                "music festivals",
                "thrifting",
                "vlogging",
                "coffee",
                "social media",
            ],
        },
        "4": {
            "age": 60,
            "gender": "male",
            "income": "$120k",
            "location": "Boston",
            "occupation": "financial analyst",
            "education": "master’s",
            "interests": ["golf", "wine", "stocks", "history", "travel"],
        },
        "5": {
            "age": 28,
            "gender": "non-binary",
            "income": "$65k",
            "location": "Seattle",
            "occupation": "graphic designer",
            "education": "bachelor’s",
            "interests": ["art", "photography", "indie music", "vegan food", "cycling"],
        },
        "6": {
            "age": 38,
            "gender": "female",
            "income": "$40k",
            "location": "Manchester",
            "occupation": "teacher",
            "education": "bachelor’s",
            "interests": [
                "reading",
                "gardening",
                "TV dramas",
                "volunteering",
                "baking",
            ],
        },
        "7": {
            "age": 54,
            "gender": "male",
            "income": "$95k",
            "location": "Toronto",
            "occupation": "architect",
            "education": "master’s",
            "interests": ["modern art", "cycling", "jazz", "cooking", "urban design"],
        },
        "8": {
            "age": 26,
            "gender": "female",
            "income": "$55k",
            "location": "Denver",
            "occupation": "marketing specialist",
            "education": "bachelor’s",
            "interests": [
                "skiing",
                "Instagram",
                "travel",
                "live music",
                "craft cocktails",
            ],
        },
        "9": {
            "age": 41,
            "gender": "male",
            "income": "$70k",
            "location": "Chicago",
            "occupation": "police officer",
            "education": "associate’s",
            "interests": [
                "baseball",
                "barbecue",
                "camping",
                "fishing",
                "community events",
            ],
        },
        "10": {
            "age": 36,
            "gender": "female",
            "income": "$80k",
            "location": "London",
            "occupation": "data analyst",
            "education": "master’s",
            "interests": ["podcasts", "Pilates", "finance", "true crime", "travel"],
        },
        "11": {
            "age": 67,
            "gender": "male",
            "income": "$42k",
            "location": "Tampa",
            "occupation": "retired electrician",
            "education": "high school",
            "interests": [
                "fishing",
                "grilling",
                "football",
                "classic cars",
                "grandkids",
            ],
        },
        "12": {
            "age": 23,
            "gender": "male",
            "income": "$28k",
            "location": "Berlin",
            "occupation": "barista",
            "education": "college dropout",
            "interests": [
                "skateboarding",
                "electronic music",
                "fashion",
                "tattoos",
                "coffee",
            ],
        },
        "13": {
            "age": 50,
            "gender": "female",
            "income": "$100k",
            "location": "Sydney",
            "occupation": "corporate lawyer",
            "education": "JD",
            "interests": ["wine", "dining out", "yoga", "theatre", "luxury travel"],
        },
        "14": {
            "age": 29,
            "gender": "male",
            "income": "$62k",
            "location": "Portland",
            "occupation": "environmental consultant",
            "education": "master’s",
            "interests": [
                "biking",
                "vegan cooking",
                "documentaries",
                "outdoor adventures",
                "ecology",
            ],
        },
        "15": {
            "age": 48,
            "gender": "female",
            "income": "$38k",
            "location": "Birmingham",
            "occupation": "nurse",
            "education": "nursing diploma",
            "interests": [
                "gardening",
                "family time",
                "charity walks",
                "reality TV",
                "cooking",
            ],
        },
        "16": {
            "age": 33,
            "gender": "male",
            "income": "$85k",
            "location": "New York City",
            "occupation": "IT consultant",
            "education": "bachelor’s",
            "interests": ["gym", "startups", "street food", "travel", "crypto"],
        },
        "17": {
            "age": 57,
            "gender": "female",
            "income": "$47k",
            "location": "Glasgow",
            "occupation": "shop manager",
            "education": "high school",
            "interests": ["baking", "soap operas", "travel shows", "family", "dogs"],
        },
        "18": {
            "age": 22,
            "gender": "female",
            "income": "$20k",
            "location": "Tokyo",
            "occupation": "fashion intern",
            "education": "college student",
            "interests": ["makeup", "K-pop", "shopping", "Instagram", "café hopping"],
        },
        "19": {
            "age": 65,
            "gender": "male",
            "income": "$30k",
            "location": "Dublin",
            "occupation": "retired bus driver",
            "education": "secondary school",
            "interests": ["football", "pub quizzes", "gardening", "radio", "neighbors"],
        },
        "20": {
            "age": 40,
            "gender": "female",
            "income": "$120k",
            "location": "Los Angeles",
            "occupation": "film producer",
            "education": "bachelor’s",
            "interests": [
                "cinema",
                "fashion",
                "networking",
                "fine dining",
                "yoga retreats",
            ],
        },
        "21": {
            "age": 19,
            "gender": "male",
            "income": "$14k",
            "location": "Madrid",
            "occupation": "student",
            "education": "high school",
            "interests": ["football", "gaming", "streetwear", "movies", "concerts"],
        },
        "22": {
            "age": 71,
            "gender": "female",
            "income": "$32k",
            "location": "Stockholm",
            "occupation": "retired nurse",
            "education": "college",
            "interests": ["knitting", "reading", "baking", "gardening", "travel"],
        },
        "23": {
            "age": 47,
            "gender": "male",
            "income": "$80k",
            "location": "Houston",
            "occupation": "oil rig manager",
            "education": "associate’s",
            "interests": [
                "water sports",
                "home improvement",
                "trucks",
                "barbecue",
                "country music",
            ],
        },
        "24": {
            "age": 35,
            "gender": "female",
            "income": "$51k",
            "location": "Vancouver",
            "occupation": "physiotherapist",
            "education": "master’s",
            "interests": [
                "road cycling",
                "hiking",
                "yoga",
                "video games",
                "science podcasts",
            ],
        },
        "25": {
            "age": 29,
            "gender": "male",
            "income": "$34k",
            "location": "Delhi",
            "occupation": "call center agent",
            "education": "bachelor’s",
            "interests": [
                "Bollywood",
                "cricket",
                "street food",
                "photography",
                "online gaming",
            ],
        },
        "26": {
            "age": 58,
            "gender": "female",
            "income": "$62k",
            "location": "Oslo",
            "occupation": "museum curator",
            "education": "PhD",
            "interests": [
                "art history",
                "reading",
                "cycling",
                "travel",
                "new cuisines",
            ],
        },
        "27": {
            "age": 27,
            "gender": "male",
            "income": "$44k",
            "location": "Cape Town",
            "occupation": "tour guide",
            "education": "college",
            "interests": [
                "wildlife",
                "surfing",
                "outdoor adventures",
                "social media",
                "local music",
            ],
        },
        "28": {
            "age": 44,
            "gender": "female",
            "income": "$70k",
            "location": "Paris",
            "occupation": "fashion buyer",
            "education": "master’s",
            "interests": [
                "designer brands",
                "fine dining",
                "art galleries",
                "travel",
                "yoga",
            ],
        },
        "29": {
            "age": 61,
            "gender": "male",
            "income": "$38k",
            "location": "Rome",
            "occupation": "taxi driver",
            "education": "secondary school",
            "interests": [
                "football",
                "local history",
                "playing cards",
                "espresso",
                "family dinners",
            ],
        },
        "30": {
            "age": 24,
            "gender": "female",
            "income": "$60k",
            "location": "Toronto",
            "occupation": "web developer",
            "education": "bachelor’s",
            "interests": [
                "coding",
                "startup events",
                "podcasts",
                "street food",
                "rollerblading",
            ],
        },
        "31": {
            "age": 55,
            "gender": "male",
            "income": "$28k",
            "location": "Warsaw",
            "occupation": "train conductor",
            "education": "high school",
            "interests": ["trains", "gardening", "folk music", "chess", "history"],
        },
        "32": {
            "age": 42,
            "gender": "female",
            "income": "$98k",
            "location": "Singapore",
            "occupation": "investment banker",
            "education": "MBA",
            "interests": [
                "fine dining",
                "investment clubs",
                "travel",
                "tennis",
                "yoga",
            ],
        },
        "33": {
            "age": 31,
            "gender": "male",
            "income": "$48k",
            "location": "Mexico City",
            "occupation": "radio DJ",
            "education": "bachelor’s",
            "interests": [
                "music production",
                "nightlife",
                "DJs",
                "comedy",
                "food trucks",
            ],
        },
        "34": {
            "age": 37,
            "gender": "female",
            "income": "$80k",
            "location": "San Diego",
            "occupation": "chiropractor",
            "education": "D.C.",
            "interests": [
                "wellness",
                "beach walks",
                "Pilates",
                "farmers markets",
                "fitness apps",
            ],
        },
        "35": {
            "age": 25,
            "gender": "male",
            "income": "$23k",
            "location": "Bangkok",
            "occupation": "street vendor",
            "education": "secondary school",
            "interests": [
                "street food",
                "Muay Thai",
                "local festivals",
                "motorbikes",
                "movies",
            ],
        },
        "36": {
            "age": 39,
            "gender": "female",
            "income": "$54k",
            "location": "Berlin",
            "occupation": "advertising consultant",
            "education": "master’s",
            "interests": [
                "art galleries",
                "electronic music",
                "travel",
                "vegan food",
                "yoga",
            ],
        },
        "37": {
            "age": 59,
            "gender": "female",
            "income": "$35k",
            "location": "Prague",
            "occupation": "retired teacher",
            "education": "bachelor’s",
            "interests": [
                "history",
                "gardening",
                "folk dance",
                "theatre",
                "cat rescue",
            ],
        },
        "38": {
            "age": 46,
            "gender": "male",
            "income": "$92k",
            "location": "Zurich",
            "occupation": "software architect",
            "education": "PhD",
            "interests": [
                "hiking",
                "skiing",
                "cryptography",
                "reading",
                "scuba diving",
            ],
        },
        "39": {
            "age": 63,
            "gender": "female",
            "income": "$37k",
            "location": "Venice",
            "occupation": "tourist guide",
            "education": "college",
            "interests": [
                "rowing",
                "Venetian history",
                "cookery",
                "photography",
                "opera",
            ],
        },
        "40": {
            "age": 22,
            "gender": "male",
            "income": "$20k",
            "location": "Seoul",
            "occupation": "university student",
            "education": "undergraduate",
            "interests": ["K-pop", "esports", "street food", "fashion", "Instagram"],
        },
        "41": {
            "age": 52,
            "gender": "female",
            "income": "$56k",
            "location": "Edinburgh",
            "occupation": "event planner",
            "education": "bachelor’s",
            "interests": [
                "festivals",
                "whisky",
                "country walks",
                "crafts",
                "food tastings",
            ],
        },
        "42": {
            "age": 30,
            "gender": "male",
            "income": "$72k",
            "location": "Helsinki",
            "occupation": "game developer",
            "education": "master’s",
            "interests": ["gaming", "hockey", "coding", "drones", "metal music"],
        },
        "43": {
            "age": 36,
            "gender": "female",
            "income": "$46k",
            "location": "Istanbul",
            "occupation": "journalist",
            "education": "bachelor’s",
            "interests": [
                "current events",
                "coffee houses",
                "writing",
                "podcasts",
                "photography",
            ],
        },
        "44": {
            "age": 27,
            "gender": "female",
            "income": "$24k",
            "location": "Jakarta",
            "occupation": "social media manager",
            "education": "high school",
            "interests": [
                "Instagram",
                "vlogging",
                "street food",
                "K-pop",
                "online shopping",
            ],
        },
        "45": {
            "age": 68,
            "gender": "male",
            "income": "$29k",
            "location": "Athens",
            "occupation": "retired postman",
            "education": "college",
            "interests": [
                "rebetiko music",
                "history",
                "café visits",
                "chess",
                "grandkids",
            ],
        },
        "46": {
            "age": 23,
            "gender": "female",
            "income": "$19k",
            "location": "Rio de Janeiro",
            "occupation": "dance instructor",
            "education": "college",
            "interests": ["samba", "beach", "movies", "fashion", "surfing"],
        },
        "47": {
            "age": 40,
            "gender": "male",
            "income": "$75k",
            "location": "Dubai",
            "occupation": "sales manager",
            "education": "bachelor’s",
            "interests": [
                "luxury cars",
                "golf",
                "travel",
                "tech gadgets",
                "fine dining",
            ],
        },
        "48": {
            "age": 34,
            "gender": "female",
            "income": "$71k",
            "location": "Melbourne",
            "occupation": "child psychologist",
            "education": "PhD",
            "interests": [
                "child development",
                "reading",
                "arts and crafts",
                "fitness",
                "community events",
            ],
        },
        "49": {
            "age": 50,
            "gender": "male",
            "income": "$33k",
            "location": "Budapest",
            "occupation": "street cleaner",
            "education": "secondary school",
            "interests": [
                "cycling",
                "folk music",
                "cooking",
                "football",
                "dog walking",
            ],
        },
        "50": {
            "age": 41,
            "gender": "female",
            "income": "$67k",
            "location": "New Orleans",
            "occupation": "chef",
            "education": "culinary school",
            "interests": [
                "jazz",
                "food festivals",
                "baking",
                "wineries",
                "cooking competitions",
            ],
        },
    }

    @classmethod
    def names(cls):
        return list(cls.PROFILES.keys())

    @classmethod
    def get(cls, *names):
        result = []
        for name in names:
            if name not in cls.PROFILES:
                raise KeyError(f"No profile named '{name}'")
            result.append(cls.PROFILES[name])
        return result

    @classmethod
    def get_all(cls):
        all_items = []
        for name in cls.names():
            all_items.append(cls.PROFILES[name])
        return all_items

    @classmethod
    def get_first_n(cls, n: int):
        result = []
        for i in range(1, n + 1):
            if str(i) in cls.PROFILES:
                result.append(cls.PROFILES[str(i)])
            else:
                break
        return result
